export type KeapEndpoint = {
  method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE';
  path: string;
  pathParams?: string[];
};

export const keapEndpoints: Record<string, KeapEndpoint> = {
  'keap_add_contacts_to_campaign_sequence': { method: 'POST', path: '/v2/campaigns/{campaign_id}/sequences/{sequence_id}:addContacts', pathParams: ["campaign_id", "sequence_id"] },
  'keap_add_product_option_list_option_value': { method: 'POST', path: '/v2/products/{product_id}/options/{product_option_id}/listItems', pathParams: ["product_id", "product_option_id"] },
  'keap_adjust_inventory': { method: 'POST', path: '/v2/products/{product_id}:adjustInventory', pathParams: ["product_id"] },
  'keap_apply_commission_on_order_items': { method: 'POST', path: '/v2/orders/{order_id}/items/{order_item_id}:applyCommission', pathParams: ["order_id", "order_item_id"] },
  'keap_apply_tags': { method: 'POST', path: '/v2/tags/{tag_id}/contacts:applyTags', pathParams: ["tag_id"] },
  'keap_apply_tax': { method: 'POST', path: '/v2/orders/{order_id}:applyTax', pathParams: ["order_id"] },
  'keap_attach_file_to_order': { method: 'POST', path: '/v2/orders/{order_id}:attachFile', pathParams: ["order_id"] },
  'keap_create_company': { method: 'POST', path: '/v2/companies' },
  'keap_create_contact': { method: 'POST', path: '/v2/contacts' },
  'keap_create_contact_link_type': { method: 'POST', path: '/v2/contacts/links/types' },
  'keap_create_email': { method: 'POST', path: '/v2/emails' },
  'keap_create_emails': { method: 'POST', path: '/v2/emails:batchAdd' },
  'keap_create_file': { method: 'POST', path: '/v2/files' },
  'keap_create_note': { method: 'POST', path: '/v2/contacts/{contact_id}/notes', pathParams: ["contact_id"] },
  'keap_create_note_custom_field': { method: 'POST', path: '/v2/notes/model/customFields' },
  'keap_create_opportunity': { method: 'POST', path: '/v2/opportunities' },
  'keap_create_opportunity_custom_fields': { method: 'POST', path: '/v2/opportunities/model/customFields' },
  'keap_create_opportunity_stage': { method: 'POST', path: '/v2/opportunities/stages' },
  'keap_create_order': { method: 'POST', path: '/v2/orders' },
  'keap_create_order_custom_field': { method: 'POST', path: '/v2/orders/model/customFields' },
  'keap_create_order_item': { method: 'POST', path: '/v2/orders/{order_id}/items', pathParams: ["order_id"] },
  'keap_create_payment_for_an_order': { method: 'POST', path: '/v2/orders/{order_id}/payments', pathParams: ["order_id"] },
  'keap_create_product': { method: 'POST', path: '/v2/products' },
  'keap_create_product_image': { method: 'POST', path: '/v2/products/{product_id}/images', pathParams: ["product_id"] },
  'keap_create_product_option': { method: 'POST', path: '/v2/products/{product_id}/options', pathParams: ["product_id"] },
  'keap_create_tag': { method: 'POST', path: '/v2/tags' },
  'keap_create_tag_category': { method: 'POST', path: '/v2/tags/categories' },
  'keap_create_task': { method: 'POST', path: '/v2/tasks' },
  'keap_create_task_custom_field': { method: 'POST', path: '/v2/tasks/model/customFields' },
  'keap_delete_company': { method: 'DELETE', path: '/v2/companies/{company_id}', pathParams: ["company_id"] },
  'keap_delete_contact': { method: 'DELETE', path: '/v2/contacts/{contact_id}', pathParams: ["contact_id"] },
  'keap_delete_email': { method: 'DELETE', path: '/v2/emails/{id}', pathParams: ["id"] },
  'keap_delete_emails': { method: 'POST', path: '/v2/emails:batchRemove' },
  'keap_delete_file': { method: 'DELETE', path: '/v2/files/{file_id}', pathParams: ["file_id"] },
  'keap_delete_note': { method: 'DELETE', path: '/v2/contacts/{contact_id}/notes/{note_id}', pathParams: ["contact_id", "note_id"] },
  'keap_delete_opportunity': { method: 'DELETE', path: '/v2/opportunities/{opportunity_id}', pathParams: ["opportunity_id"] },
  'keap_delete_opportunity_stage': { method: 'DELETE', path: '/v2/opportunities/stages/{stage_id}', pathParams: ["stage_id"] },
  'keap_delete_order': { method: 'DELETE', path: '/v2/orders/{order_id}', pathParams: ["order_id"] },
  'keap_delete_order_custom_field': { method: 'DELETE', path: '/v2/orders/model/customFields/{custom_field_id}', pathParams: ["custom_field_id"] },
  'keap_delete_order_item': { method: 'DELETE', path: '/v2/orders/{order_id}/items/{order_item_id}', pathParams: ["order_id", "order_item_id"] },
  'keap_delete_product': { method: 'DELETE', path: '/v2/products/{product_id}', pathParams: ["product_id"] },
  'keap_delete_product_image': { method: 'DELETE', path: '/v2/products/{product_id}/images', pathParams: ["product_id"] },
  'keap_delete_product_option': { method: 'DELETE', path: '/v2/products/{product_id}/options/{product_option_id}', pathParams: ["product_id", "product_option_id"] },
  'keap_delete_product_option_list_option_value': { method: 'DELETE', path: '/v2/products/{product_id}/options/{product_option_id}/listItems/{item_id}', pathParams: ["product_id", "product_option_id", "item_id"] },
  'keap_delete_tag': { method: 'DELETE', path: '/v2/tags/{tag_id}', pathParams: ["tag_id"] },
  'keap_delete_tag_category': { method: 'DELETE', path: '/v2/tags/categories/{tag_category_id}', pathParams: ["tag_category_id"] },
  'keap_delete_task': { method: 'DELETE', path: '/v2/tasks/{task_id}', pathParams: ["task_id"] },
  'keap_delete_task_custom_field': { method: 'DELETE', path: '/v2/tasks/model/customFields/{custom_field_id}', pathParams: ["custom_field_id"] },
  'keap_detach_file_from_order': { method: 'POST', path: '/v2/orders/{order_id}:detachFile', pathParams: ["order_id"] },
  'keap_get_campaign': { method: 'GET', path: '/v2/campaigns/{campaign_id}', pathParams: ["campaign_id"] },
  'keap_get_campaign_goals': { method: 'GET', path: '/v2/campaigns/{campaign_id}/goals', pathParams: ["campaign_id"] },
  'keap_get_campaign_sequences': { method: 'GET', path: '/v2/campaigns/{campaign_id}/sequences', pathParams: ["campaign_id"] },
  'keap_get_category': { method: 'GET', path: '/v2/tags/categories/{tag_category_id}', pathParams: ["tag_category_id"] },
  'keap_get_company': { method: 'GET', path: '/v2/companies/{company_id}', pathParams: ["company_id"] },
  'keap_get_contact': { method: 'GET', path: '/v2/contacts/{contact_id}', pathParams: ["contact_id"] },
  'keap_get_email': { method: 'GET', path: '/v2/emails/{id}', pathParams: ["id"] },
  'keap_get_email_address_status': { method: 'GET', path: '/v2/emailAddresses/{email}/status', pathParams: ["email"] },
  'keap_get_email_template': { method: 'GET', path: '/v2/emails/templates/{email_template_id}', pathParams: ["email_template_id"] },
  'keap_get_file': { method: 'GET', path: '/v2/files/{file_id}', pathParams: ["file_id"] },
  'keap_get_file_data': { method: 'GET', path: '/v2/files/{file_id}:data', pathParams: ["file_id"] },
  'keap_get_html': { method: 'GET', path: '/v2/webforms/{webform_id}:data', pathParams: ["webform_id"] },
  'keap_get_note': { method: 'GET', path: '/v2/contacts/{contact_id}/notes/{note_id}', pathParams: ["contact_id", "note_id"] },
  'keap_get_opportunity': { method: 'GET', path: '/v2/opportunities/{opportunity_id}', pathParams: ["opportunity_id"] },
  'keap_get_opportunity_stage': { method: 'GET', path: '/v2/opportunities/stages/{stage_id}', pathParams: ["stage_id"] },
  'keap_get_order': { method: 'GET', path: '/v2/orders/{order_id}', pathParams: ["order_id"] },
  'keap_get_product': { method: 'GET', path: '/v2/products/{product_id}', pathParams: ["product_id"] },
  'keap_get_product_option': { method: 'GET', path: '/v2/products/{product_id}/options/{product_option_id}', pathParams: ["product_id", "product_option_id"] },
  'keap_get_tag': { method: 'GET', path: '/v2/tags/{tag_id}', pathParams: ["tag_id"] },
  'keap_get_task': { method: 'GET', path: '/v2/tasks/{task_id}', pathParams: ["task_id"] },
  'keap_get_user_by_id': { method: 'GET', path: '/v2/users/{user_id}', pathParams: ["user_id"] },
  'keap_get_user_group': { method: 'GET', path: '/v2/userGroups/{user_group_id}', pathParams: ["user_group_id"] },
  'keap_get_user_info': { method: 'GET', path: '/v2/oauth/connect/userinfo' },
  'keap_get_user_signature': { method: 'GET', path: '/v2/users/{user_id}/signature', pathParams: ["user_id"] },
  'keap_link_contacts': { method: 'POST', path: '/v2/contacts:link' },
  'keap_list_campaigns': { method: 'GET', path: '/v2/campaigns' },
  'keap_list_companies': { method: 'GET', path: '/v2/companies' },
  'keap_list_companies_for_tag_id': { method: 'GET', path: '/v2/tags/{tag_id}/companies', pathParams: ["tag_id"] },
  'keap_list_contact_link_types': { method: 'GET', path: '/v2/contacts/links/types' },
  'keap_list_contact_links': { method: 'GET', path: '/v2/contacts/{contact_id}/links', pathParams: ["contact_id"] },
  'keap_list_contacts': { method: 'GET', path: '/v2/contacts' },
  'keap_list_contacts_with_tag_id': { method: 'GET', path: '/v2/tags/{tag_id}/contacts', pathParams: ["tag_id"] },
  'keap_list_emails': { method: 'GET', path: '/v2/emails' },
  'keap_list_files': { method: 'GET', path: '/v2/files' },
  'keap_list_note_templates': { method: 'GET', path: '/v2/notes/templates' },
  'keap_list_notes': { method: 'GET', path: '/v2/contacts/{contact_id}/notes', pathParams: ["contact_id"] },
  'keap_list_opportunities': { method: 'GET', path: '/v2/opportunities' },
  'keap_list_opportunity_stages': { method: 'GET', path: '/v2/opportunities/stages' },
  'keap_list_order_payments': { method: 'GET', path: '/v2/orders/{order_id}/payments', pathParams: ["order_id"] },
  'keap_list_orders': { method: 'GET', path: '/v2/orders' },
  'keap_list_paginated_users': { method: 'GET', path: '/v2/users' },
  'keap_list_product_options': { method: 'GET', path: '/v2/products/{product_id}/options', pathParams: ["product_id"] },
  'keap_list_products': { method: 'GET', path: '/v2/products' },
  'keap_list_tag_categories': { method: 'GET', path: '/v2/tags/categories' },
  'keap_list_tags': { method: 'GET', path: '/v2/tags' },
  'keap_list_tags_for_contact': { method: 'GET', path: '/v2/contacts/{contact_id}/tags', pathParams: ["contact_id"] },
  'keap_list_tasks': { method: 'GET', path: '/v2/tasks' },
  'keap_list_user_groups': { method: 'GET', path: '/v2/userGroups' },
  'keap_list_webforms': { method: 'GET', path: '/v2/webforms' },
  'keap_remove_contacts_from_campaign_sequence': { method: 'POST', path: '/v2/campaigns/{campaign_id}/sequences/{sequence_id}:removeContacts', pathParams: ["campaign_id", "sequence_id"] },
  'keap_remove_tags': { method: 'POST', path: '/v2/tags/{tag_id}/contacts:removeTags', pathParams: ["tag_id"] },
  'keap_retrieve_contact_model': { method: 'GET', path: '/v2/contacts/model' },
  'keap_retrieve_note_model': { method: 'GET', path: '/v2/notes/model' },
  'keap_retrieve_order_custom_field_model': { method: 'GET', path: '/v2/orders/model' },
  'keap_retrieve_task_model': { method: 'GET', path: '/v2/tasks/model' },
  'keap_send_email': { method: 'POST', path: '/v2/emails:send' },
  'keap_send_email_template': { method: 'POST', path: '/v2/emails/templates:send' },
  'keap_unlink_contacts': { method: 'POST', path: '/v2/contacts:unlink' },
  'keap_update_company': { method: 'PATCH', path: '/v2/companies/{company_id}', pathParams: ["company_id"] },
  'keap_update_contact': { method: 'PATCH', path: '/v2/contacts/{contact_id}', pathParams: ["contact_id"] },
  'keap_update_email_address_opt_status': { method: 'PATCH', path: '/v2/emailAddresses/{email}/status', pathParams: ["email"] },
  'keap_update_file': { method: 'POST', path: '/v2/files/{file_id}', pathParams: ["file_id"] },
  'keap_update_note': { method: 'PATCH', path: '/v2/contacts/{contact_id}/notes/{note_id}', pathParams: ["contact_id", "note_id"] },
  'keap_update_notes_custom_field': { method: 'PATCH', path: '/v2/notes/model/customFields/{custom_field_id}', pathParams: ["custom_field_id"] },
  'keap_update_opportunity': { method: 'PATCH', path: '/v2/opportunities/{opportunity_id}', pathParams: ["opportunity_id"] },
  'keap_update_opportunity_custom_field': { method: 'PATCH', path: '/v2/opportunities/model/customFields/{custom_field_id}', pathParams: ["custom_field_id"] },
  'keap_update_opportunity_stage': { method: 'PATCH', path: '/v2/opportunities/stages/{stage_id}', pathParams: ["stage_id"] },
  'keap_update_order': { method: 'PATCH', path: '/v2/orders/{order_id}', pathParams: ["order_id"] },
  'keap_update_order_custom_field': { method: 'PATCH', path: '/v2/orders/model/customFields/{custom_field_id}', pathParams: ["custom_field_id"] },
  'keap_update_order_item': { method: 'PATCH', path: '/v2/orders/{order_id}/items/{order_item_id}', pathParams: ["order_id", "order_item_id"] },
  'keap_update_product': { method: 'PATCH', path: '/v2/products/{product_id}', pathParams: ["product_id"] },
  'keap_update_product_option': { method: 'PATCH', path: '/v2/products/{product_id}/options/{product_option_id}', pathParams: ["product_id", "product_option_id"] },
  'keap_update_product_option_list_option_value': { method: 'PATCH', path: '/v2/products/{product_id}/options/{product_option_id}/listItems/{item_id}', pathParams: ["product_id", "product_option_id", "item_id"] },
  'keap_update_tag': { method: 'PATCH', path: '/v2/tags/{tag_id}', pathParams: ["tag_id"] },
  'keap_update_tag_category': { method: 'PATCH', path: '/v2/tags/categories/{tag_category_id}', pathParams: ["tag_category_id"] },
  'keap_update_task': { method: 'PATCH', path: '/v2/tasks/{task_id}', pathParams: ["task_id"] },
  'keap_update_task_custom_field': { method: 'PATCH', path: '/v2/tasks/model/customFields/{custom_field_id}', pathParams: ["custom_field_id"] },
  'keap_update_user': { method: 'PATCH', path: '/v2/users/{user_id}', pathParams: ["user_id"] },
};
